spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ef1e0cc671832e61f21d
            client-secret: 3f54097390fd6b89306b0a0c3e1be31769d135e4
            scope: read:user,repo
            redirect-uri: http://localhost:9495/login/oauth2/code/github
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id


github:
  baseUrl: https://api.github.com



server:
  port: 9495
